@extends('layouts.app')

@section('title', 'Financial Data List Report')

@section('content')
    <div class="container">
        <!-- Filter Section -->
        <div class="card mb-4">
            <div class="card-header bg-light">
                <i class="fas fa-filter"></i> Filtered Details
            </div>
            <div class="card-body">
                <div class="row mt-3">
                    <div class="col-md-12 d-flex justify-content-between align-items-center flex-column flex-md-row">
                        <div>
                            @if (request()->filled('start_date'))
                                <span class="badge bg-secondary">Start Date: {{ request('start_date') }}</span>
                            @endif
                            @if (request()->filled('end_date'))
                                <span class="badge bg-secondary">End Date: {{ request('end_date') }}</span>
                            @endif
                            @if (request()->filled('user_id'))
                                <span class="badge bg-info">User:
                                    {{ \App\Models\User::find(request('user_id'))->name ?? 'N/A' }}
                                </span>
                            @endif
                            @if (request()->filled('type'))
                                <span class="badge bg-primary">Payment Method: {{ ucfirst(request('type')) }}</span>
                            @endif
                            @if (request()->filled('bill'))
                                <span class="badge bg-danger">Bill Number: {{ request('bill') }}</span>
                            @endif
                            @if (request()->filled('source'))
                                <span class="badge bg-success">
                                    Source:
                                    @if (request('source') == 'collection')
                                        Collection Only
                                    @elseif (request('source') == 'bill')
                                        Bill Only
                                    @else
                                        Both
                                    @endif
                                </span>
                            @endif
                        </div>
                        Generated By: {{ auth()->user()->name }} on {{ now() }}
                    </div>
                </div>
            </div>
        </div>

        <!-- Financial Data Table -->
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Date</th>
                        <th>Bill Number</th>
                        <th>Customer</th>
                        <th>Amount</th>
                        <th>Payment Method</th>
                        <th>User</th>
                    </tr>
                </thead>
                <tbody>
                    @php $grandTotal = 0; @endphp
                    @forelse ($allData as $row)
                        @php $grandTotal += $row['amount']; @endphp
                        <tr>
                            <td>
                                @if($row['source'] === 'collection')
                                    <span class="badge bg-info">Collection</span>
                                @else
                                    <span class="badge bg-success">Bill</span>
                                @endif
                            </td>
                            <td>{{ $row['date'] ?? '-' }}</td>
                            <td>
                                @if($row['bill_number'])
                                    {{ $row['bill_number'] }}
                                @else
                                    <span class="text-muted">-</span>
                                @endif
                            </td>
                            <td>{{ $row['customer_name'] ?? '-' }}</td>
                            <td>{{ number_format($row['amount'], 2) }}</td>
                            <td>{{ ucfirst($row['payment_method'] ?? '-') }}</td>
                            <td>{{ $row['user_name'] ?? '-' }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="text-center text-muted">No financial data found for the selected filters.</td>
                        </tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" class="text-end fw-bold">Total:</td>
                        <td class="fw-bold">{{ number_format($grandTotal, 2) }}</td>
                        <td colspan="2"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <!-- Print Styles -->
    <style>
        @media print {
            table {
                width: 100%;
                border-collapse: collapse;
                table-layout: fixed;
                font-size: 45%;
            }
            th,
            td {
                border: 1px solid black;
                padding: 8px;
                word-wrap: break-word;
                text-align: left;
            }
            .table-responsive {
                overflow: visible !important;
            }
        }
    </style>

    <script>
        window.print();
    </script>
@endsection
