@extends('layouts.app')

@section('title', 'Overdue Payments Report')

@section('content')
    <div class="container">

        <!-- Filter Section -->
        <div class="card mb-4">
            <div class="card-header bg-light">
                <i class="fas fa-filter"></i> Filtered Details
            </div>
            <div class="card-body">
                <div class="row mt-3">
                    <div class="col-md-12 d-flex justify-content-between align-items-center flex-column flex-md-row">
                        <div>
                            @if (request()->filled('overdue_days'))
                                <span class="badge bg-secondary">Overdue Days: {{ request('overdue_days') }}</span>
                            @endif
                            @if (request()->filled('customer_name') ||
                                    request()->filled('bill_number') ||
                                    request()->filled('hometown_value') ||
                                    request()->filled('customer_nic') ||
                                    request()->filled('customer_mobile'))
                                <span class="badge bg-danger me-1">Filters Applied:</span>
                                @if (request()->filled('customer_name'))
                                    <span class="badge bg-danger">Customer Name: {{ request('customer_name') }}</span>
                                @endif
                                @if (request()->filled('bill_number'))
                                    <span class="badge bg-danger">Bill Number: {{ request('bill_number') }}</span>
                                @endif
                                @if (request()->filled('hometown_value'))
                                    <span class="badge bg-danger">Hometown: {{ request('hometown_value') }}</span>
                                @endif
                                @if (request()->filled('customer_nic'))
                                    <span class="badge bg-danger">NIC: {{ request('customer_nic') }}</span>
                                @endif
                                @if (request()->filled('customer_mobile'))
                                    <span class="badge bg-danger">Mobile: {{ request('customer_mobile') }}</span>
                                @endif
                            @endif
                        </div>
                        Generated By: {{ auth()->user()->name }} on {{ now() }}
                    </div>
                </div>
            </div>
        </div>

        <!-- Overdue Payments Table -->
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                    <tr>
                        <th class="table-header">
                            <a href="{{ route('reports.overdue', array_merge(request()->all(), ['sort_by' => 'bill_number', 'sort_order' => request('sort_order') == 'asc' ? 'desc' : 'asc'])) }}"
                                class="text-decoration-none text-white">
                                Bill Number <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th class="table-header"><i class="fas fa-user"></i> Customer</th>
                        <th class="table-header"><i class="fas fa-phone"></i> Mobile</th>
                        <th class="table-header"><i class="fas fa-phone-square"></i> Contact</th>
                        <th class="table-header"><i class="fas fa-home"></i> Home Town</th>
                        <th class="table-header"><i class="fas fa-dollar-sign"></i> Total Price</th>
                        <th class="table-header"><i class="fas fa-dollar-sign"></i> Advance</th>
                        <th class="table-header"><i class="fas fa-dollar-sign"></i> Balance</th>
                        <th class="table-header"><i class="fas fa-calendar-day"></i> Next Payment Date</th>
                        <th class="table-header"><i class="fas fa-money-bill-wave-alt"></i> Next Payment Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($installments as $bill)
                        <tr>
                            <td>
                                <b class="{{ $bill->category == 0 ? 'text-primary' : 'text-success' }}">
                                    <a href="{{ route('bills.show', $bill) }}" class="text-decoration-none text-reset">
                                        {{ $bill->bill_number }}
                                    </a>
                                </b>
                            </td>
                            <td>
                                <b>
                                    <a href="{{ route('customers.show', $bill->customer->id) }}"
                                        class="text-decoration-none text-reset">
                                        {{ $bill->customer->name }}
                                    </a>
                                </b>
                            </td>
                            <td>{{ $bill->customer->mobile }}</td>
                            <td>{{ $bill->customer->contact }}</td>
                            <td>{{ $bill->customer->hometownValue->value ?? 'N/A' }}</td>
                            <td>{{ number_format($bill->total_price, 2) }}</td>
                            <td>{{ number_format($bill->advance_payment, 2) }}</td>
                            <td>{{ number_format($bill->balance, 2) }}</td>
                            <td>{{ $bill->next_bill }}</td>
                            <td>{{ number_format($bill->next_payment, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="10" class="text-center text-muted">No overdue payments found for the selected
                                date range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Print Styles -->
    <style>
        @media print {
            table {
                width: 100%;
                border-collapse: collapse;
                table-layout: fixed;
                font-size: 45%;
            }

            th,
            td {
                border: 1px solid black;
                padding: 8px;
                word-wrap: break-word;
                text-align: left;
            }

            .table-responsive {
                overflow: visible !important;
            }
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function(tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        });

        window.print();
    </script>
@endsection
