@extends('layouts.app')

@section('title', 'Collected Payments Report')

@section('content')
    <div class="container">
        <!-- Filter Section -->
        <div class="card mb-4">
            <div class="card-header bg-light">
                <i class="fas fa-filter"></i> Filtered Details
            </div>
            <div class="card-body">
                <div class="row mt-3">
                    <div class="col-md-12 d-flex justify-content-between align-items-center flex-column flex-md-row">
                        <div>
                            @if (request()->filled('start_date'))
                                <span class="badge bg-secondary">Start Date: {{ request('start_date') }}</span>
                            @endif
                            @if (request()->filled('end_date'))
                                <span class="badge bg-secondary">End Date: {{ request('end_date') }}</span>
                            @endif
                            @if (request()->filled('customer_name') || request()->filled('bill_number'))
                                <span class="badge bg-danger me-1">Filters Applied:</span>
                                @if (request()->filled('customer_name'))
                                    <span class="badge bg-danger">Customer Name: {{ request('customer_name') }}</span>
                                @endif
                                @if (request()->filled('bill_number'))
                                    <span class="badge bg-danger">Bill Number: {{ request('bill_number') }}</span>
                                @endif
                            @endif
                        </div>
                        Generated By: {{ auth()->user()->name }} on {{ now() }}
                    </div>
                </div>
            </div>
        </div>

        <!-- Collected Payments Table -->
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                    <tr>
                        <th class="table-header"><i class="fas fa-calendar-day"></i> Date</th>
                        <th class="table-header"><i class="fas fa-hashtag"></i> Bill Number</th>
                        <th class="table-header"><i class="fas fa-user"></i> Customer</th>
                        <th class="table-header"><i class="fas fa-phone"></i> Mobile</th>
                        <th class="table-header"><i class="fas fa-phone-square"></i> Contact</th>
                        <th class="table-header"><i class="fas fa-home"></i> Home Town</th>
                        <th class="table-header"><i class="fas fa-user-circle"></i> Collected By</th>
                        <th class="table-header"><i class="fas fa-money-bill-wave-alt"></i> Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($collections as $collection)
                        <tr>
                            <td>{{ $collection->date }}</td>
                            <td>
                                @if ($collection->bill)
                                    <a href="{{ route('bills.show', $collection->bill) }}"
                                        class="text-decoration-none text-reset">
                                        {{ $collection->bill->bill_number }}
                                    </a>
                                @else
                                    N/A
                                @endif
                            </td>
                            <td>
                                @if ($collection->bill && $collection->bill->customer)
                                    <a href="{{ route('customers.show', $collection->bill->customer->id) }}"
                                        class="text-decoration-none text-reset">
                                        {{ $collection->bill->customer->name }}
                                    </a>
                                @else
                                    N/A
                                @endif
                            </td>
                            <td>
                                {{ $collection->bill->customer->mobile ?? 'N/A' }}
                            </td>
                            <td>
                                {{ $collection->bill->customer->contact ?? 'N/A' }}
                            </td>
                            <td>
                                {{ $collection->bill->customer->hometownValue->value ?? 'N/A' }}
                            </td>
                            <td>
                                {{ $collection->user->name ?? 'N/A' }}
                            </td>
                            <td>
                                {{ number_format($collection->amount, 2) }}
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="text-center text-muted">No collected payments found for the selected
                                date range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Print Styles -->
    <style>
        @media print {
            table {
                width: 100%;
                border-collapse: collapse;
                table-layout: fixed;
                font-size: 45%;
            }

            th,
            td {
                border: 1px solid black;
                padding: 8px;
                word-wrap: break-word;
                text-align: left;
            }

            .table-responsive {
                overflow: visible !important;
            }
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function(tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        });

        window.print();
    </script>
@endsection
